version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    command: >
      -c work_mem=50MB
      -c seq_page_cost=0.8
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c checkpoint_completion_target=0.9
      -c jit_optimize_above_cost=3000000
      -c jit_inline_above_cost=1000000
      -c jit_above_cost=3000000
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      start_period: 30s
